server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
    session:
      timeout: 60

spring:
  profiles:
    active: local
    include: security
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/loginService?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 7893
  jpa:
    hibernate:
      ddl-auto: create

#p6spy
decorator:
  datasource:
    p6spy:
      enable-logging: true